server:
  port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: zxhbwdke87kbnbei
        url: jdbc:mysql://jfrpocyduwfg38kq.chr7pe7iynqr.eu-west-1.rds.amazonaws.com/q5k6nwov3rat2rjq
        username: wuf793zaxl7njty4
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        #defer-datasource-initialization: true 
    sql:
      init:
        data-locations: classpath:technology_insert.sql
        #mode: always            
     
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    try-it-out-enabled: false
    default-model-expand-depth: -1
    
logging:
  level:
    '[org.springframework.security]': DEBUG
jwt:
  secretKey: secrets8o7gvk7icretsecret1
  tokenPrefix: "Bearer "
