#server:
#  port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: bwi28owobb6oxd0q
        url: jdbc:mysql://r4wkv4apxn9btls2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/e4sjnnk6oityuwu9
        username: e1qp8tuxf3rp5p2n
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        #defer-datasource-initialization: true 
    sql:
      init:
        data-locations: classpath:technology_insert.sql
        #mode: always            
     
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    try-it-out-enabled: false
    default-model-expand-depth: -1
    
logging:
  level:
    '[org.springframework.security]': DEBUG
jwt:
  secretKey: secrets8o7gvk7icretsecret1
  tokenPrefix: "Bearer "
